server:
  port: 8333

spring:
  application:
    name: server-gateway


  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        cluster-name: gateway  #设置集群名称
#        namespace: 8ab1173d-c1e7-4d64-a441-9326483eea4a  #设置命名空间
        ephemeral: true  #更改为不是临时实例(false)

    gateway:
      discovery:
        locator:
          enabled: true

      routes:
          - id: server-co
            uri: lb://server-co
            predicates:
              - Path=/server/**
          - id: server-rsa
            uri: lb://server-rsa
            predicates:
              - Path=/RSA/**


filter:
  config:
    excludeUrls: /server/login/,/RSA/getPublicKey  #登录和注册不需过滤，直接放行

