server:
  port: 8333

spring:
  application:
    name: server-gateway


  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    gateway:
      discovery:
        locator:
          enabled: true

      routes:
          - id: server-co
            uri: lb://server-co
            predicates:
              - Path=/server/**

